apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-api-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://user-api-auth-service.default.svc.cluster.local/auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-token
    nginx.ingress.kubernetes.io/auth-method: GET
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-api-app-service
                port:
                  number: {{ .Values.service.appPort }}