replicaCount: 1

image:
  repo: bogadukhovd/user-api-auth

service:
  type: NodePort
  appPort: "8000"

ingress:
  host: user-api-app-service.default.svc.cluster.local
  host2: arch.homework

auth:
  authServicePort: "8111"
  secret: verySecretString