apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ include "user-api-auth-chart.fullname" . }}
  labels:
    {{- include "user-api-auth-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-api-auth-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "user-api-auth-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repo }}:{{ .Chart.AppVersion }}"
        ports:
          - name: http
            containerPort: {{ .Values.auth.authServicePort }}
            protocol: TCP
        envFrom:  
          - configMapRef:
              name: auth-config
          - secretRef:
              name: auth-secrets
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          tcpSocket:
            port: {{ .Values.auth.authServicePort }}
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.auth.authServicePort }}
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10