apiVersion: v1
kind: Service
metadata:
  name: user-api-auth-service
  labels:
    {{- include "user-api-auth-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "user-api-auth-chart.selectorLabels" . | nindent 4 }}
  type: NodePort
  ports: 
  - port:  80
    targetPort: {{ .Values.auth.authServicePort }}