apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    {{- include "user-api-auth-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports: 
  - name:  auth
    port:  {{ .Values.auth.authServicePort }}
    targetPort: {{ .Values.auth.authServicePort }}
    protocol: TCP