apiVersion: v1
kind: Service
metadata:
  name: user-api-app-service
  labels:
    app: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}
  ports: 
  - name:  web
    port:  {{ .Values.service.appPort }}
    targetPort: {{ .Values.service.appPort }}
    protocol: TCP