

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uesr-api # Перезаписываем уже существующий ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://http://arch.homework//auth
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-token
spec:
  rules:
    - http:
        paths:
          - path: / # Направляем все запросы к echoserver
            pathType: Prefix
            backend:
              service:
                name: uesr-api-service
                port:
                  number: 8000