apiVersion: apps/v1 
kind: Deployment                                  # Type of the kubernetes resource
metadata:
  name: user-api-app                  # Name of the Kubernetes resource
  labels:
    app: user-api-app  
spec:
  replicas: 1                                     # Number of pods to run at any given time
  selector:
    matchLabels: 
      app: user-api-app                 # This deployment applies to any Pods matching the specified label
  template:                                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                     # The labels that will be applied to all of the pods in this deployment
        app: user-api-app
    spec:                                         # Spec for the container which will run in the Pod
      containers:
      - name: user-api-app 
        image: bogadukhovd/otus-user-api:1.5.0       # The image we are getting from dockerhub
        ports:
          - name: http
            containerPort: 8000                   # Should match the port number that the Go application listens on
        envFrom:  
          - secretRef:
              name: user-api-db-secrets             # Name of the secret environmental variable file to load
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 500Mi
        #livenessProbe:
        #  tcpSocket:
        #    port: 8000
        #  initialDelaySeconds: 5
        #  timeoutSeconds: 5
        #  successThreshold: 1
        #  failureThreshold: 3
        #  periodSeconds: 10
        #readinessProbe:
        #  httpGet:
        #    path: /health
        #    port: 8000
        #  initialDelaySeconds: 5
        #  timeoutSeconds: 2
        #  successThreshold: 1
        # failureThreshold: 3
        # periodSeconds: 10